### ISSUE TITLE
Dependency versioning

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/emissions-api#75]
How do we want to keep track of dependency versions?

We recently had the problem that we had a breaking change in one of our libraries (in fact, in our own library :wink:) which made me think about how we track libraries. In that particular case, I've just required a version greater or equal to the new version:

https://github.com/emissions-api/emissions-api/blob/1de7010c0ce91fd41abe567a95ec7b7f00fec08b/requirements.txt#L8

This, however, may mean that future library versions with breaking changes may be okay as well.

That is the reason for a lot of projects to freeze the library versions using something like this in the `requirements.txt`:

    dependency==version

But this may be hard for dependencies like `gdal` which we prefer to install using a system package manager and which version might hence slightly differ.

That is why my suggestion would be to:

- Freeze the version of dependencies without C-library backends
- Leave dependencies with accompanying C-libraries untouched or set them to a version range if required
- Integrate [Dependabot](https://dependabot.com/) to take care of dependency updates (meaning that the bot would automatically create pull requests for new library versions which we would still need to test)

Thoughts?

**Comment by shaardie** [comment]
Great having someone to think about those kind of problems :smile: 

I like the idea of having a automation around the dependency management. And I also like the idea of automatically finding security problems in dependencies. So changes in our dependency management that make such automation possible do have my support.

Is a hard dependency freeze (==) needed for those tools? And are there problems with mixed python environments (--system-site-packages)? Otherwise I would also be happy with minimal versions (>=) for now. If and when we think about an automatic deployment to production, we should reconsider this and probably stick to a hard dependency freeze.

I also agree that it would be hard to freeze the dependencies with C Library backends. We would have to streamline our development for that.

**Comment by shaardie** [comment]
We talked about this in detail and we will introduce @lkiesow proposal. I created #80 for that.
